#!/usr/bin/env osascript

if application "Google Chrome" is running then
  tell application "Google Chrome" to get URL of active tab of first window
else if application "Safari" is running then
  tell application "Safari" to get URL of current tab of first window
end if

### brurl ends here
